def get_food_descriptions() -> dict[str, str]:
    """
    Return a mapping from class label to an English description.
    """
    return {
        "apple_pie": "Apple pie, a quintessential American dessert, features a flaky crust filled with sweet, spiced apples. Originating from English settlers, it symbolizes home comfort and is often enjoyed during Thanksgiving with a scoop of vanilla ice cream.",
        "baby_back_ribs": "Baby back ribs, a staple of American barbecue, are tender pork ribs slathered in smoky, tangy sauce. Popular in Southern U.S. culture, they’re grilled or slow-cooked for gatherings like tailgates or summer cookouts.",
        "baklava": "Baklava, a sweet Middle Eastern pastry, layers crispy phyllo dough with nuts and honey syrup. Originating from the Ottoman Empire, it’s a festive treat in Turkish and Greek cultures, often served during celebrations.",
        "beef_carpaccio": "Beef carpaccio, an elegant Italian appetizer, consists of thinly sliced raw beef drizzled with olive oil and lemon. Originating in Venice in the 1950s, it’s a sophisticated dish served in fine dining settings.",
        "beef_tartare": "Beef tartare, a French delicacy, features finely chopped raw beef mixed with spices, onions, and a raw egg yolk. Popular in European bistros, it reflects a bold culinary tradition of raw meat appreciation.",
        "beet_salad": "Beet salad, rooted in Eastern European cuisine, combines roasted beets with greens, goat cheese, and nuts. A vibrant dish in modern Western menus, it’s celebrated for its earthy flavors and colorful presentation.",
        "beignets": "Beignets, fluffy French doughnuts dusted with powdered sugar, are a New Orleans icon. Introduced by French settlers in Louisiana, they’re a breakfast staple, often paired with café au lait in Creole culture.",
        "bibimbap": "Bibimbap, a vibrant Korean rice bowl, mixes vegetables, meat, egg, and spicy gochujang sauce. A symbol of balance in Korean cuisine, it’s served in a sizzling stone pot for family meals or celebrations.",
        "bread_pudding": "Bread pudding, a comforting British dessert, transforms stale bread into a warm, spiced custard dish. Popular in Southern U.S. cuisine, it’s often drizzled with bourbon sauce for festive occasions.",
        "breakfast_burrito": "Breakfast burrito, a Tex-Mex creation, wraps eggs, bacon, cheese, and potatoes in a flour tortilla. Originating in the American Southwest, it’s a hearty morning dish loved for its portability and bold flavors.",
        "bruschetta": "Bruschetta, a rustic Italian appetizer, tops toasted bread with fresh tomatoes, basil, and olive oil. Originating in central Italy, it celebrates simplicity and is a staple at summer gatherings or wine tastings.",
        "caesar_salad": "Caesar salad, invented in Tijuana, Mexico, by Italian chef Caesar Cardini, features romaine lettuce, croutons, and creamy dressing. A global favorite, it’s a classic in American and European dining culture.",
        "cannoli": "Cannoli, a Sicilian dessert, are crispy pastry tubes filled with sweet ricotta and chocolate chips. A symbol of Italian celebration, they’re enjoyed during festivals like Carnevale and family gatherings in Italy.",
        "caprese_salad": "Caprese salad, from Italy’s Campania region, layers fresh tomatoes, mozzarella, and basil with balsamic glaze. Reflecting Italian simplicity, it’s a summer staple, often served as a patriotic nod to Italy’s flag colors.",
        "carrot_cake": "Carrot cake, a British wartime dessert, is a moist spice cake with carrots and cream cheese frosting. Popular in American bakeries, it’s a cozy treat for holidays like Easter or autumn gatherings.",
        "ceviche": "Ceviche, a Latin American dish from Peru, features raw fish marinated in lime juice with onions and chili. A coastal delicacy, it’s central to Peruvian culture and enjoyed during warm-weather celebrations.",
        "cheesecake": "Cheesecake, inspired by ancient Greek recipes, is a creamy dessert with a graham cracker crust. The New York-style version, rich and dense, is a global icon, often topped with berries for special occasions.",
        "cheese_plate": "Cheese plate, a European tradition, showcases assorted cheeses with fruits, nuts, and crackers. Common in French and Italian aperitivo culture, it’s a sophisticated starter for wine tastings or dinner parties.",
        "chicken_curry": "Chicken curry, rooted in South Asian cuisine, simmers tender chicken in a fragrant, spicy sauce. A staple in Indian and Thai households, it’s shared during family meals and festivals like Diwali.",
        "chicken_quesadilla": "Chicken quesadilla, a Mexican-American fusion, fills a tortilla with melted cheese, chicken, and salsa. Popular in U.S. casual dining, it’s a crowd-pleaser at game nights or family dinners.",
        "chicken_wings": "Chicken wings, an American bar food classic, are crispy and tossed in buffalo or barbecue sauce. Originating in Buffalo, New York, they’re a Super Bowl staple, embodying casual U.S. food culture.",
        "chocolate_cake": "Chocolate cake, a universal dessert, is a rich, moist treat layered with chocolate frosting. Rooted in European baking traditions, it’s a birthday favorite worldwide, symbolizing celebration and indulgence.",
        "chocolate_mousse": "Chocolate mousse, a French dessert, is a light, airy blend of chocolate and whipped cream. Served chilled in elegant settings, it reflects France’s refined pastry culture and is a romantic treat.",
        "churros": "Churros, a Spanish fried dough snack, are dusted with cinnamon sugar and dipped in chocolate. A street food favorite in Spain and Latin America, they’re enjoyed during festivals or morning coffee breaks.",
        "clam_chowder": "Clam chowder, a New England classic, is a creamy soup with clams, potatoes, and onions. Served in a bread bowl, it’s a comforting dish tied to American coastal fishing traditions.",
        "club_sandwich": "Club sandwich, an American invention, stacks turkey, bacon, lettuce, and tomato between toasted bread. A diner favorite since the early 20th century, it’s a symbol of classic U.S. lunch culture.",
        "crab_cakes": "Crab cakes, a Chesapeake Bay specialty, are golden patties of crab meat and spices. Central to Maryland’s seafood culture, they’re served with tartar sauce at coastal gatherings.",
        "creme_brulee": "Creme brulee, a French dessert, is a silky custard with a caramelized sugar crust. A staple in Parisian patisseries, it’s a luxurious treat for special occasions, embodying culinary elegance.",
        "croque_madame": "Croque madame, a French bistro classic, is a grilled ham and cheese sandwich topped with a fried egg. Popular in Parisian cafés, it’s a comforting lunch dish with rich cultural roots.",
        "cup_cakes": "Cupcakes, an American baking tradition, are small cakes topped with colorful frosting and sprinkles. A staple at birthday parties and bake sales, they reflect U.S. celebratory food culture.",
        "deviled_eggs": "Deviled eggs, a Southern U.S. appetizer, are hard-boiled eggs filled with a creamy, tangy yolk mix. Common at picnics and holiday gatherings, they’re a nostalgic dish in American cuisine.",
        "donuts": "Donuts, an American breakfast treat, are sweet fried dough rings, glazed or filled with cream. Popularized by U.S. chains like Dunkin’, they’re a morning ritual paired with coffee.",
        "dumplings": "Dumplings, a Chinese culinary staple, are dough pockets filled with meat or vegetables, steamed or fried. Eaten during Lunar New Year, they symbolize prosperity in Asian cultures.",
        "edamame": "Edamame, young soybeans from Japan, are steamed and salted for a healthy snack. A common izakaya dish, they reflect Japanese simplicity and are enjoyed with beer or sake.",
        "eggs_benedict": "Eggs benedict, an American brunch classic, layers poached eggs and ham with hollandaise sauce. Originating in New York City, it’s a luxurious dish for weekend gatherings.",
        "escargots": "Escargots, a French delicacy, are snails baked in garlic butter and served with bread. A symbol of haute cuisine, they’re enjoyed during festive meals in France’s Burgundy region.",
        "falafel": "Falafel, a Middle Eastern street food, are crispy chickpea balls served in pita with tahini. Originating in Egypt, they’re a vegan staple in Levantine cultures, loved for their bold flavors.",
        "filet_mignon": "Filet mignon, a French-inspired steak, is a tender beef cut grilled to perfection. A fine dining favorite in Western cuisine, it’s served with sauces for special occasions.",
        "fish_and_chips": "Fish and chips, a British classic, pairs crispy battered fish with thick-cut fries. Originating in 19th-century England, it’s a pub staple, tied to coastal working-class culture.",
        "foie_gras": "Foie gras, a French luxury, is a rich duck or goose liver pate with a buttery texture. Central to Gascony’s culinary heritage, it’s served during holidays or gourmet events.",
        "french_fries": "French fries, a Belgian invention, are crispy potato sticks enjoyed worldwide. A fast-food icon in American culture, they’re served with ketchup or mayo at casual meals.",
        "french_onion_soup": "French onion soup, a Parisian classic, is a savory broth with caramelized onions and cheesy bread. Rooted in French peasant cuisine, it’s a cozy dish for winter evenings.",
        "french_toast": "French toast, known as pain perdu in France, is bread soaked in egg batter and fried. A breakfast favorite in Western cultures, it’s served with syrup for family mornings.",
        "fried_calamari": "Fried calamari, an Italian-American appetizer, features crispy squid rings with marinara sauce. Popular in U.S. coastal restaurants, it reflects Italy’s seafood tradition adapted for casual dining.",
        "fried_rice": "Fried rice, a Chinese staple, stir-fries rice with vegetables, egg, and meat in soy sauce. A versatile dish in Asian households, it’s a comfort food for everyday meals.",
        "frozen_yogurt": "Frozen yogurt, an American dessert, is a tangy, creamy alternative to ice cream with toppings. Popularized in the 1980s, it’s a health-conscious treat in U.S. food culture.",
        "garlic_bread": "Garlic bread, an Italian-American side, is crusty bread slathered with garlic butter and baked. A pizzeria staple, it complements pasta dishes in Western dining traditions.",
        "gnocchi": "Gnocchi, an Italian dish from Northern Italy, are soft potato dumplings served with sauce. A comfort food in Italian culture, they’re enjoyed during family dinners or festivals.",
        "greek_salad": "Greek salad, from the Mediterranean, mixes tomatoes, cucumbers, feta, and olives with olive oil. A staple in Greek tavernas, it embodies the region’s fresh, healthy culinary ethos.",
        "grilled_cheese_sandwich": "Grilled cheese sandwich, an American classic, melts cheese between buttery, toasted bread. A nostalgic comfort food, it’s a childhood favorite in U.S. households, often paired with soup.",
        "grilled_salmon": "Grilled salmon, a Pacific Northwest favorite, is a flaky fish fillet seasoned with herbs or lemon. Celebrated in Native American cuisine, it’s a healthy dish for modern diets.",
        "guacamole": "Guacamole, a Mexican dip, blends creamy avocado with lime, cilantro, and tomatoes. Originating with the Aztecs, it’s a festive staple at Mexican celebrations like Cinco de Mayo.",
        "gyoza": "Gyoza, Japanese dumplings, are pan-fried with pork or vegetable fillings, served with soy sauce. Adapted from Chinese jiaozi, they’re a popular izakaya dish in Japan’s casual dining culture.",
        "hamburger": "Hamburger, an American icon, is a juicy beef patty with toppings in a bun. Born in the U.S. in the late 19th century, it’s a global symbol of fast food culture.",
        "hot_and_sour_soup": "Hot and sour soup, a Chinese classic, balances spicy and tangy flavors with tofu and mushrooms. A staple in Sichuan cuisine, it’s a warming starter for family meals.",
        "hot_dog": "Hot dog, an American street food, is a grilled sausage in a bun with mustard or relish. Originating from German immigrants, it’s a baseball game staple in U.S. culture.",
        "huevos_rancheros": "Huevos rancheros, a Mexican breakfast, layers fried eggs on tortillas with salsa and beans. Rooted in rural Mexican farms, it’s a hearty dish for morning gatherings.",
        "hummus": "Hummus, a Middle Eastern dip, blends chickpeas with tahini, lemon, and garlic. Originating in the Levant, it’s a shared mezze dish in Arab and Israeli culinary traditions.",
        "ice_cream": "Ice cream, a global dessert, is a creamy frozen treat with origins in ancient Persia. Popularized in Europe and America, it’s a summer favorite in countless flavors.",
        "lasagna": "Lasagna, an Italian classic from Emilia-Romagna, layers pasta with meat sauce and cheese. A Sunday dinner staple in Italian families, it’s a symbol of hearty comfort food.",
        "lobster_bisque": "Lobster bisque, a French seafood soup, is a creamy blend of lobster and sherry. Originating in coastal France, it’s a luxurious dish for upscale dining or celebrations.",
        "lobster_roll_sandwich": "Lobster roll, a New England specialty, serves chilled lobster meat in a buttery bun. Tied to Maine’s fishing culture, it’s a summer delicacy at coastal shacks.",
        "macaroni_and_cheese": "Macaroni and cheese, a Southern U.S. comfort food, is creamy pasta baked with cheese. A soul food classic, it’s a nostalgic dish for American family gatherings.",
        "macarons": "Macarons, a French confection, are delicate cookies with a crisp shell and creamy filling. Originating in Parisian patisseries, they’re a symbol of French elegance at tea parties.",
        "miso_soup": "Miso soup, a Japanese staple, is a soothing broth with fermented soybean paste and tofu. Central to daily meals in Japan, it reflects the culture’s focus on umami and balance.",
        "mussels": "Mussels, a Belgian and French dish, are steamed in white wine or tomato broth. A coastal favorite, they’re shared in European bistros, symbolizing communal dining.",
        "nachos": "Nachos, a Tex-Mex creation, layer tortilla chips with cheese, jalapeños, and salsa. Originating in Northern Mexico, they’re a game-day favorite in American and Mexican cultures.",
        "omelette": "Omelette, a French breakfast dish, is a fluffy egg fold with cheese or vegetable fillings. A versatile staple in European cuisine, it’s a quick meal for any time of day.",
        "onion_rings": "Onion rings, an American side dish, are crispy, deep-fried onion slices with a savory coating. A diner classic, they’re a popular accompaniment to burgers in U.S. food culture.",
        "oysters": "Oysters, a global seafood delicacy, are served raw with lemon or mignonette, originating in coastal regions. In French and American oyster bars, they’re a luxurious treat tied to maritime traditions.",
        "pad_thai": "Pad Thai, Thailand’s national dish, stir-fries rice noodles with shrimp, peanuts, and tamarind sauce. A street food icon, it reflects Thailand’s vibrant, balanced culinary heritage.",
        "paella": "Paella, a Spanish dish from Valencia, combines saffron rice with seafood, chicken, and vegetables. A communal meal for fiestas, it embodies Spain’s rich Mediterranean food culture.",
        "pancakes": "Pancakes, an American breakfast classic, are fluffy cakes served with syrup and butter. Rooted in European traditions, they’re a family favorite for weekend mornings in the U.S.",
        "panna_cotta": "Panna cotta, an Italian dessert from Piedmont, is a silky custard topped with berry sauce. A light, elegant treat, it’s a staple in Italian restaurants and celebrations.",
        "peking_duck": "Peking duck, a Chinese delicacy, is crispy roasted duck served with pancakes and hoisin sauce. Originating in Beijing, it’s a ceremonial dish for banquets in Chinese culture.",
        "pho": "Pho, a Vietnamese noodle soup, features fragrant beef or chicken broth with rice noodles and herbs. A street food staple, it’s a symbol of Vietnam’s rich culinary heritage.",
        "pizza": "Pizza, an Italian icon from Naples, is a dough base topped with tomato sauce, cheese, and ingredients. A global favorite, it represents Italy’s culinary influence and casual dining culture.",
        "pork_chop": "Pork chop, a Western classic, is a juicy, grilled pork cut often served with applesauce. Popular in American and European cuisines, it’s a hearty dish for family dinners.",
        "poutine": "Poutine, a Canadian dish from Quebec, tops fries with cheese curds and gravy. A late-night favorite, it embodies Quebec’s indulgent, working-class food culture.",
        "prime_rib": "Prime rib, an American roast, is a tender beef cut slow-cooked with herbs. A holiday centerpiece in U.S. dining, it’s served with horseradish for festive gatherings.",
        "pulled_pork_sandwich": "Pulled pork sandwich, a Southern U.S. barbecue dish, is slow-cooked pork in a bun. Central to Carolina food culture, it’s a staple at picnics and cook-offs.",
        "ramen": "Ramen, a Japanese noodle soup, combines savory broth with pork, seaweed, and egg. Evolving from Chinese origins, it’s a comfort food in Japan’s vibrant street food scene.",
        "ravioli": "Ravioli, an Italian pasta from Liguria, are pockets filled with cheese or meat in sauce. A family favorite, they’re a symbol of Italy’s regional culinary diversity.",
        "red_velvet_cake": "Red velvet cake, a Southern U.S. dessert, is a red-hued cake with cream cheese frosting. A soul food classic, it’s a festive treat for birthdays and holidays.",
        "risotto": "Risotto, an Italian dish from Lombardy, is creamy rice cooked with broth and parmesan. A labor-intensive dish, it’s a fine dining staple in Northern Italian cuisine.",
        "samosa": "Samosa, an Indian snack, is a crispy pastry filled with spiced potatoes or meat. A street food favorite, it’s shared during festivals like Holi across South Asia.",
        "sashimi": "Sashimi, a Japanese delicacy, is thinly sliced raw fish served with soy sauce and wasabi. Rooted in Japan’s sushi culture, it celebrates the purity of fresh seafood.",
        "scallops": "Scallops, a global seafood dish, are seared to a golden crust with butter sauce. Popular in French and American fine dining, they reflect coastal culinary traditions.",
        "seaweed_salad": "Seaweed salad, a Japanese side dish, marinates seaweed with sesame and vinegar. A staple in sushi restaurants, it embodies Japan’s focus on light, umami-rich flavors.",
        "shrimp_and_grits": "Shrimp and grits, a Southern U.S. dish, pairs creamy grits with sautéed shrimp. Rooted in Lowcountry cuisine, it’s a soul food classic for hearty meals.",
        "spaghetti_bolognese": "Spaghetti bolognese, an Italian dish from Bologna, is pasta with a rich meat sauce. A global comfort food, it’s a family favorite in Italian and Western cuisines.",
        "spaghetti_carbonara": "Spaghetti carbonara, a Roman classic, tosses pasta with egg, pecorino, and guanciale. A symbol of Italian simplicity, it’s a beloved dish in trattorias worldwide.",
        "spring_rolls": "Spring rolls, a Chinese appetizer, are crispy rolls filled with vegetables or shrimp. Popular in Asian cultures, they’re a festive dish for Lunar New Year celebrations.",
        "steak": "Steak, a Western favorite, is a grilled beef cut served with sides like potatoes. Central to American and Argentine barbecue cultures, it’s a symbol of hearty dining.",
        "strawberry_shortcake": "Strawberry shortcake, an American dessert, layers biscuits with strawberries and whipped cream. A summer classic, it’s a nostalgic treat at U.S. picnics and fairs.",
        "sushi": "Sushi, a Japanese art form, combines vinegared rice with raw fish or vegetables. Originating in Edo-period Japan, it’s a global symbol of precision and culinary elegance.",
        "tacos": "Tacos, a Mexican street food, fill corn tortillas with meat, salsa, and avocado. Rooted in indigenous traditions, they’re a vibrant part of Mexico’s festive food culture.",
        "takoyaki": "Takoyaki, a Japanese snack, are octopus-filled batter balls drizzled with sauce. A street food from Osaka, they’re a fun, casual dish at festivals and markets.",
        "tiramisu": "Tiramisu, an Italian dessert from Veneto, layers coffee-soaked ladyfingers with mascarpone cream. A modern classic, it’s a romantic treat in Italian cafés and celebrations.",
        "tuna_tartare": "Tuna tartare, a global appetizer, is diced raw tuna with soy sauce and avocado. Inspired by French tartare, it’s a trendy dish in upscale Asian and Western restaurants.",
        "waffles": "Waffles, a Belgian breakfast dish, are crispy grids served with syrup or whipped cream. Popularized in America, they’re a cozy staple for family brunches and diners."
    }